[package]
name = "chess_vision"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "chess_vision"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
image = "0.24"
imageproc = "0.23"
ndarray = "0.15"
ndarray-stats = "0.5"
num-traits = "0.2"
